# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Norwich Hackspace Coding Club - Minecraft Site
email: cjheath@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to the Norwich Hackspace Coding Club. This site is to give you instructions on how to setup your computer before sessions as well as exercises you can complete during and outside of sessions.
baseurl: "/minecraft-setup" # the subpath of your site, e.g. /blog
url: "http://norwich-hackspace-codingclub.github.io/minecraft-setup/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown